### ISSUE TITLE
mpv.conf doesn't get loaded

### ISSUE THREAD

**Issue by bionade24** [minnyres/mpv-windows-arm64#1]
I tried to place my mpv config in both the PWD of the binary as well as in the `%APPDATA%` path that the mpv website suggests, but none of the configuration is applied when starting mpv. I can enable HW decoding by pressing Ctrl+H just fine.

**Comment by minnyres** [comment]
Hi. I tried put `mpv.conf` at the directory `C:\Users\<user_name>\AppData\Roaming\mpv`, which seems work for me.

**Comment by bionade24** [comment]
The hwdec option I set (dxva2) doesn't work on my machine, hence I believed it's not working. Actually, it works fine on both places.
